## 301114 Nature of Data course
### Autumn Semester 2019
### Assignment


# REMINDERS

- Finish part e of question 4 (use F-test?)
- Finish the last part of question 1.
- Does the Ph.D awarded question just mean CS degrees?
- Add mean to the boxplots for pima women.
- Does it matter if we assume CS degrees or Cheese is the independent variable?

Use this jupyter notebook as your starting point to do the assignment. It must be uploaded with all solutions to the vuws website.

Make sure to have each segment of R code in cells after each part of the question, together with executed results, so that we are able to independently verify the results.

**Submission deadline:**  5th June, 23:00

Late submissions will receive a 10\% reduction in marks for each day late.

The assignment is worth 40% of the overall mark for the course.

Question 1 is worth 12 marks, question 2 is worth 12, and question 3 is worth 14 marks.

#### Question 1

Consider the following data set of per capita consumption of mozzarella cheese and computer science degrees awarded,
for years 2000 to 2009.

In [2]:
# Per capita consumption of mozzarella cheese (US)
# 2000 to 2009
# (in lbs) 

cheese <- c(9.3,9.7,9.7,9.7,9.9,10.2,10.5,11,10.6,10.6)

# Computer science doctorates awarded (US)
csdegrees <- c(861,830,809,867,948,1129, 1453, 1656, 1787, 1611)

(a) Plot the most appropriate graph to determine if the data is correlated

In [3]:
options(repr.plot.width = 8, repr.plot.height = 5)
plot(csdegrees, cheese, xlab = "CS degrees awarded (US)", ylab = "Per capita mozzarella (US)", main = "CS degrees vs mozzarella cheese
consumption", pch = 16, col = "blue")

(b) Run the best test to determine linear correlation together with calculated 95% confidence intervals  

In [4]:
# Run a Pearson's product-moment correlation test to determine the correlation between csdegrees awarded in the US from 2001-2009 and
# mozarella cheese consumption per capita in the US. 

cor_test <- cor.test(csdegrees, cheese, conf.level = 0.95)
cat("p-value: ", cor_test$p.value, "\n")

cat("Linear Correlation: ", cor_test$estimate, "\n", "95% Confidence interval: ", cor_test$conf.int)

p-value:  0.0001059155 
Linear Correlation:  0.9283097 
 95% Confidence interval:  0.7188325 0.9832424

(c) Can you conclude the datasets are correlated? Give an explanation for why you think it is/is not the case

Yes, we can conclude the data sets are correlated. This is because the p-value given by the pearson test is 0.0001 which is statistically significant if we assume an $\alpha$ of 0.05 and even 0.01. Using the permutation test below as well where the redline on the histogram indicates where the observed linear correlation value would lie, we can conclude similar results as it is outside the bounds of the critical values for when $\alpha$ is 0.05. 

In [5]:
options(repr.plot.width = 8, repr.plot.height = 5)
x <- replicate(1000, {
    perm.csdegrees <- sample(csdegrees, replace = TRUE)
    sim <- cor.test(perm.csdegrees, cheese, conf.level = 0.95)$estimate
    })

hist(x, col = 'lightblue', main = "Histogram of correlations")

abline(v = c(cor_test$estimate), col = 'red')

# critical p values.
crit_p <- quantile(x, c(0.025, 0.975))
abline(v = crit_p, col = 'darkblue')

# P test
p_val <- mean(x>cor_test$estimate)+ mean(x < -cor_test$estimate)
p_val

[1] 0

(d) Perform a least-squares fit, plotting the original data points plus the appropriate line on the same graph.

In [6]:
# using the lienar model function to find the 'fitted' values of 'a' and 'b' to draw the line of best fit.
options(repr.plot.width = 8, repr.plot.height = 5)
fcc <- lm(cheese~csdegrees, data = as.data.frame(cbind(csdegrees, cheese)))
plot(csdegrees, cheese, xlab = "CS degrees awarded (US)", ylab = "Per capita mozzarella (US)", main = "CS degrees vs mozzarella cheese
consumption", pch = 16)
abline(fcc, col = 'red')

(d) Do you think looking at the line, that this fit is a good explanation? Please give reasons for your choice. Then, using a test given already in the course, plot a graph to demonstrate if this is indeed a good fit.

Yes, the fit, from inspection, seems to be a good explanation of the trend of the data. This is because the fit seems to minimize the distance between all the data points as we can see from the line and it also shows a positive relationship between the two variables which seems to be the case from superficial inspection of the data points on the plot. Also the datapoints tend to indicate a linear trend which is being shown by the line.

However, to see if this is actually a good fit, we should plot a residual graph which should give us a more exact understanding of the how the residuals are scattered. 

In [7]:
options(repr.plot.width = 8, repr.plot.height = 5)
plot(csdegrees, residuals(fcc), main = "Residuals", pch = 16)
abline(h=0)

Here we can see that in general, the residuals are scattered evenly above and below the 0 horizontal line, so it seems to show the residuals don't follow any particular trend which indicates the linear model is a good fit.

(e) Can we conclude that computer science PhD awards affect mozzerella cheese consumption ? Explain your answer.

- Correlation doesn't imply causation. 

We cannot conclude that computer science Ph.D awards affect mozzerella cheese consumption because correlation doesn't imply casuation. There could be many reasons as to why computer science Ph.D awards and mozzerella cheese consumption seem to have a positive linear relationship. One could be due to a third variable that affects both Ph.D computer science awards and mozzerella cheese consumption.

- Ph.D awards may only be a small subset of actual CS degrees awarded, so we can't conclude the weight they have on the correlations or possible causation. 

(f) Give two suggested improvements to this test to improve the quality of the possible conclusions, explaining
why in each case these would help.

#### Question 2

(a) Download the dataset from https://www.kaggle.com/kumargh/pimaindiansdiabetescsv

This contains information about the Pima people from North America.  A number of social and environmental factors have contributed to them having one of the highest rates of type 2 diabetes in the world. This data set contains information of around 700 female individuals, including
* ever.pregnant — Whether the individual has ever been pregnant
* diastolic — diastolic blood pressure
* bmi — Body Mass Index
* age — age in years




## Load the data set.

In [8]:
pima <- read.csv("Data sets/pima-indians-diabetes.csv")

dimnames(pima)[[2]] <- c("preg", "plas", "pres", "skin", "test", "mass", "pedi", "age", "class")

head(pima, 15)

preg plas pres skin test mass pedi  age class
1   1    85  66   29     0  26.6 0.351 31  0    
2   8   183  64    0     0  23.3 0.672 32  1    
3   1    89  66   23    94  28.1 0.167 21  0    
4   0   137  40   35   168  43.1 2.288 33  1    
5   5   116  74    0     0  25.6 0.201 30  0    
6   3    78  50   32    88  31.0 0.248 26  1    
7  10   115   0    0     0  35.3 0.134 29  0    
8   2   197  70   45   543  30.5 0.158 53  1    
9   8   125  96    0     0   0.0 0.232 54  1    
10  4   110  92    0     0  37.6 0.191 30  0    
11 10   168  74    0     0  38.0 0.537 34  1    
12 10   139  80    0     0  27.1 1.441 57  0    
13  1   189  60   23   846  30.1 0.398 59  1    
14  5   166  72   19   175  25.8 0.587 51  1    
15  7   100   0    0     0  30.0 0.484 32  1

(b) Is there evidence that body mass index differs for women who have had a pregnancy versus those that haven’t? In what direction is any difference? 

Use a t test to see if there is difference in the means between the two groups. 

$H_0, mu=0$:no difference in mean BMI for the two groups.

$H_1, mu!=0$: there is a difference in mean between the two groups. 

Is there a direction for the difference? which tail? 

In [9]:
# calculate the mean BMI for women who have been pregnant and those who have not been pregnant. 
# pregnant women
pregnant_df <- pima[pima['preg'] > 0, ]
BMI_pregnant <- pregnant_df$mass
mean(BMI_pregnant)

# non-pregnant
non_pregdf <- pima[pima['preg'] == 0,]
BMI_no_preg <- non_pregdf$mass
mean(BMI_no_preg)

#t.test
t.test(BMI_pregnant, BMI_no_preg, var.equal = FALSE)

[1] 31.60137

[1] 34.29009


	Welch Two Sample t-test

data:  BMI_pregnant and BMI_no_preg
t = -2.6296, df = 129.36, p-value = 0.009585
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -4.711682 -0.665754
sample estimates:
mean of x mean of y 
 31.60137  34.29009 


The t.test above shows a statistical significant difference between the means of pregnant pima women versus those who have not been pregnant where $p = 0.0099$ and a t value of $t = -2.6296$. There is a negative difference in that the mean of pregnant women have a lower BMI those who have not been pregnant. The t-value is in the direction of the left tail.

(c) Make an appropriate plot of the data.

In [10]:
# Use a box and whisker plot to display the data. 
options(repr.plot.width = 8, repr.plot.height = 5)
par(mar=c(5,9,4,1)+.1)
boxplot(BMI_pregnant, BMI_no_preg, main = "BMI's between groups", at = c(1,2), names = c("been pregnant", "never pregnant"), 
        col = c("lightblue", "lightgreen"), horizontal = TRUE, las =2, xlab = "BMI")

Diastolic blood pressure is thought to vary by age. 

(d) Make an appropriate plot of the data. 

In [11]:
rbPal <- colorRampPalette(c('orange','red'))
pima$Col <- rbPal(20)[as.numeric(cut(pima$pres,breaks = 20))]

plot(pima$pres~pima$age, type = 'p', main = "Diastolic blood pressure vs age", xlab = "Age (Years)", 
     ylab = "Diastolic blood pressure (mm Hg)", col = pima$Col, pch = 16)

(e) Compute a 95% confidence interval for the Pearson correlation of age and diastolic blood pressure in female Pima people.

In [12]:
pearson_blood.age <- cor.test(pima$age, pima$pres, conf.level = 0.95)
cat("The Pearson correlation coefficient is:", pearson_blood.age$estimate, "\n")
cat("The 95% confidence interval for the Preason correlation of age and blood pressure is :", pearson_blood.age$conf.int)

The Pearson correlation coefficient is: 0.239571 
The 95% confidence interval for the Preason correlation of age and blood pressure is : 0.1716924 0.3051857

(f) Fit the simple linear regression of diastolic and age. Interpret the slope of the regression. Compute a 95% confidence interval for the mean diastolic blood pressure of a 40 year old female of the Pima people.

In [13]:
blood_fit <- lm(pres~age, data = pima)
pima$Col <- rbPal(20)[as.numeric(cut(pima$pres,breaks = 20))]
plot(pima$pres~pima$age, type = 'p', main = "Diastolic blood pressure vs age", xlab = "Age (Years)", 
     ylab = "Diastolic blood pressure (mm Hg)", col = pima$Col, pch = 16, lwd = 4)
abline(blood_fit, col = 'darkgreen')

blood_fit[[1]][2] # the slope of the equation.

#95% confidence interval for the mean diastolic blood pressure of a 40 yr old female of the Pima people.
confint(blood_fit)
# predicted mean of diastolic blood pressure when pima female is 40 years old.
predict(blood_fit, newdata=data.frame(age=c(40)))
# 95 % confidence interval for predicted mean
predict(blood_fit, newdata =data.frame(age=c(40)), interval ="conf")

age 
0.3948206

2.5 %      97.5 %    
(Intercept) 51.9848586 59.9874121
age          0.2812579  0.5083833

1 
71.77896

fit      lwr      upr     
1 71.77896 70.23886 73.31905

### Interpretation

The slope of the regression $b = 0.395$ can be interpreted as saying for every 1 unit increase in age (1 unit being 1 year in this case), there is a 0.39 unit increase in diastolic blood pressure. 

The predicted mean diastolic blood pressure for a pima indian woman at age 40 is $71.78 mm Hg$. This is within a 95% confidence interval of $70.24 mm Hg$ to $73.32 mm Hg$. 

#### Question 3

(a) Download the data from vuws called project.csv. 

Each row of the file is an observation relating to one person from Australia. The file contains the variables:
* City: The city in which the person lives.
* Movie: A movie that the person most recently watched.
* Age: The age of the person.
* Rating: The rating (out of 10) that the person gave the movie.

# Load project dataset.

In [14]:
project <- read.csv("Data sets/project.csv")
head(project, 10)
dim(project)

City      Movie                  Age Rating
1  Sydney    Undergoal              24  8     
2  Melbourne The Cat with Two Tales 27  8     
3  Melbourne The Cat with Two Tales 15  8     
4  Melbourne The Cat with Two Tales 30  7     
5  Perth     Washing Dishes 3       46  8     
6  Brisbane  The Cat with Two Tales 14  8     
7  Sydney    The Cat with Two Tales 33  9     
8  Sydney    The Cat with Two Tales 23  7     
9  Brisbane  Undergoal              27  8     
10 Melbourne Undergoal              36  9

[1] 1000    4

##### Representative Sample
Our sample is from the six Australian cities with population counts shown below.

| City | Population | Proportion |
| ------------- |:-------------:| -----:|
| Sydney | 5,131,326 | 0.321 |
| Melbourne | 4,850,740 | 0.304 |
| Brisbane | 2,408,223 | 0.151 |
| Adelaide | 1,313,927 | 0.082 |
| Perth | 2,050,138 | 0.128 |
| Hobart | 226,884 | 0.014 |


(b) test if the distribution of cities in the data matches the above population proportions of the cities.

Goodness of fit test

calculate the expected values for the population count data. 

In [15]:
# calculate the expected values for the population count data
prop <- c(0.321, 0.304, 0.151, 0.082, 0.128, 0.014)
cities  <- c("Sydney", "Melbourne", "Brisbane", "Adelaide", "Perth", "Hobart")

# expected values
e <- (length(project$City)*prop)
names(e) <- cities
e

#observed values
obs_val <- table(project$City)[c("Sydney", "Melbourne", "Brisbane", "Adelaide", "Perth", "Hobart")]
obs_val

chi_fit <- sum((obs_val-e)^2/e)
chi_fit

# simulation of chi-square distribution where df = 5
set.seed(1)
x = replicate(10000, {
    counts = rmultinom(1, 1000, prop)
    chisq = sum((counts-e)^2/e)
})
mean(x>chi_fit)

hist(x, col = 'lightgreen', main = "Chi-square distribution, df = 5", xlab = "Chi-Square value", breaks = 20)
abline(v = chi_fit, col = 'red')
abline(v = quantile(x, c(0.95)), col = 'blue')

Sydney Melbourne  Brisbane  Adelaide     Perth    Hobart 
      321       304       151        82       128        14


   Sydney Melbourne  Brisbane  Adelaide     Perth    Hobart 
      325       295       148       101       113        18 

[1] 7.679003

[1] 0.1711

Yes the sample data matches the above propotions of the population of the cities. The sample data has a p value of $p = 0.1711$ so it is not statistically significant, it is within the bounds of the expected values.

#### Chosen Movie

It is believed that people from difference cities have different preferences. 

(c) Is there a dependence between the sample variables City and Chosen Movie?

In [16]:
# create a contingency table
ctable <- table(project[c("City", "Movie")])
ctable
total_row <- as.vector(apply(ctable, 1, sum))
ctable <- cbind(ctable, total_row)
total_col <- as.vector(apply(ctable, 2, sum))
ctable <- rbind(ctable, total_col)
ctable

chisq.test(ctable[1:6, 1:3])

           Movie
City        The Cat with Two Tales Undergoal Washing Dishes 3
  Adelaide                      52        15               34
  Brisbane                      80        23               45
  Hobart                         9         5                4
  Melbourne                    166        59               70
  Perth                         55        27               31
  Sydney                       187        55               83

The Cat with Two Tales Undergoal Washing Dishes 3 total_row
Adelaide   52                     15        34               101     
Brisbane   80                     23        45               148     
Hobart      9                      5         4                18     
Melbourne 166                     59        70               295     
Perth      55                     27        31               113     
Sydney    187                     55        83               325     
total_col 549                    184       267              1000

Warning message in chisq.test(ctable[1:6, 1:3]):
“Chi-squared approximation may be incorrect”


	Pearson's Chi-squared test

data:  ctable[1:6, 1:3]
X-squared = 10.375, df = 10, p-value = 0.4082


There is currently no reason to accept the alternative hypothesis that movie preference and the city a person resides in is dependent. The p value of the chi-squared test for independence is $p = 0.4082$, which is greater than the 0.05 significance level. Thus we do not reject the null hypothesis that movie preference and the city a person resides in is independent. 

#### Harsh Raters

As people grow older, it is believed that they expect more from movies and so provide lower ratings. 

(d) To answer this question, test if there is a difference in the mean rating for people over and including 40 years old, compared to the mean rating from people under 40 years old.

In [38]:
forty.and.over <- project[c(project["Age"] >= 40), "Rating" ]
under.forty <- project[c(project["Age"] < 40), "Rating" ]
mean_40plus <- mean(forty.and.over)
mean_under40 <- mean(under.forty)

# Means of ratings.
mean_40plus
mean_under40

t.test(forty.and.over, under.forty, alternative = "less")

[1] 7.056701

[1] 7.401985


	Welch Two Sample t-test

data:  forty.and.over and under.forty
t = -5.7077, df = 293.34, p-value = 1.401e-08
alternative hypothesis: true difference in means is less than 0
95 percent confidence interval:
      -Inf -0.245464
sample estimates:
mean of x mean of y 
 7.056701  7.401985 


The Null hypothesis $H_{0}$ for this test is that difference in the mean ratings for movies between those who are forty and over, versus those who are under 40 is zero (0) - there is no statistically significant difference in the means. 

The alternative hypothesis $H_{a}$ however, is that older people (those forty and over) expect more from movies, thus the overall mean ratings for forty and over's should be less than that of those under forty. Therefore the alternative hypothesis is that $\mu_{older} < \mu_{younger}$ thus the true difference in means should be less than 0 ($\mu_{older}-\mu_{younger} < 0$).

As the t-test shows, there is a statistially significant difference with the t-value, giving a p-value of $ p=1.041x10^{-8}$. Therefore we should reject the null hypothesis and accept the alternative, that the true difference is means is less than zero, which is the hypothesis that older people tend to rate movies lower than younger people since they expect more.

#### Best Movie

(e) Is there evidence that the movies are not equally preferred? Test if all mean ratings are equal for each movie? If there is not equal preference, which is preferred over which?

- Use F test.

#### Age and Ratings

(f) We found that older people rate movies lower. Using a linear model of Rating as a function of Age, is there evidence that the gradient is not zero? Use the model to predict the expected rating for someone of age 32.

In [74]:
#linear model function
fit_ratings <- lm(Rating~Age, data = project)
fit_ratings
# coef(fit_ratings) - allows us to extract intercept and gradient from the fitted model if we want.
summary(fit_ratings)
# predict expected rating for somebody of age 32
#direct
exp_rat_32 <- coef(fit_ratings)[[2]]*32 + coef(fit_ratings)[[1]]
exp_rat_32
#using predict function
predict_32 <- predict(fit_ratings, newdata =data.frame(Age=c(32)))
cat("The expected rating for a movie given by somebody of the age 32 is: ", predict_32[[1]])


Call:
lm(formula = Rating ~ Age, data = project)

Coefficients:
(Intercept)          Age  
    7.94582     -0.01961  



Call:
lm(formula = Rating ~ Age, data = project)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.0635 -0.4557 -0.1616  0.5836  2.5443 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept)  7.945823   0.073595 107.966   <2e-16 ***
Age         -0.019607   0.002239  -8.756   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.7414 on 998 degrees of freedom
Multiple R-squared:  0.07134,	Adjusted R-squared:  0.07041 
F-statistic: 76.67 on 1 and 998 DF,  p-value: < 2.2e-16


[1] 7.318413

The expected rating for a movie given by somebody of the age 32 is:  7.318413

- gradient statistically significant - not zero
- expected rating for somebody 32 - 7.32